export enum ShelterTypes {
    FETCH_SHELTERS = "FETCH_SHELTERS", 
    FETCH_SHELTER = "FETCH_SHELTER", 
    POST_SHELTER = "POST_SHELTER", 
    PUT_SHELTER = "PUT_SHELTER", 
    DELETE_SHELTER = "DELETE_SHELTER", 
}
export enum AnimalTypes {
    FETCH_ANIMAL = "FETCH_ANIMAL",
    POST_ANIMAL = "POST_ANIMAL",
    PUT_ANIMAL = "PUT_ANIMAL",
    DELETE_ANIMAL = "DELETE_ANIMAL",
    ARCHIVE_ANIMAL = "ARCHIVE_ANIMAL"
}
export enum NeedTypes {
    FETCH_NEED = "FETCH_NEED",
    POST_NEED = "POST_NEED",
    PUT_NEED = "PUT_NEED",
    DELETE_NEED = "DELETE_NEED"
}
export enum VolunteerTypes {
    FETCH_VOLUNTEER = "FETCH_VOLUNTEER",
    POST_VOLUNTEER = "POST_VOLUNTEER",
    PUT_VOLUNTEER = "PUT_VOLUNTEER",
    DELETE_VOLUNTEER = "DELETE_VOLUNTEER",
    ATTACHE_VOLUNTEER_ANIMAL = "ATTACHE_VOLUNTEER_ANIMAL",
    DEATTACHE_VOLUNTEER_ANIMAL = "DEATTACHE_VOLUNTEER_ANIMAL",
    DEATTACHE_VOLUNTEER_SHELTER = "DEATTACHE_VOLUNTEER_SHELTER",
    ATTACHE_VOLUNTEER_SHELTER = "ATTACHE_VOLUNTEER_SHELTER"
}

export enum AppTypes{
    SHOW_LOADER = "SHOW_LOADER",
    HIDE_LOADER = "HIDE_LOADER"
}

export enum FormTypes{
    LOAD = "LOAD"
}