// <auto-generated />
using System;
using Mekhnin.Shelter.Data.Shelter.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Mekhnin.Shelter.Data.Shelter.Migrations
{
    [DbContext(typeof(ShelterContext))]
    partial class ShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Age")
                        .HasColumnName("age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasColumnName("bio")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<string>("ImgUrl")
                        .HasColumnName("img_url")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<string>("Race")
                        .HasColumnName("race")
                        .HasColumnType("text");

                    b.Property<int>("ShelterId")
                        .HasColumnName("shelter_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShelterId");

                    b.ToTable("animals");
                });

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Type")
                        .HasColumnName("type")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnName("value")
                        .HasColumnType("text");

                    b.Property<int>("VolunteerId")
                        .HasColumnName("volunteer_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerId");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.Need", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("AnimalId")
                        .HasColumnName("animal_id")
                        .HasColumnType("integer");

                    b.Property<int>("Count")
                        .HasColumnName("count")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDone")
                        .HasColumnName("is_done")
                        .HasColumnType("boolean");

                    b.Property<int>("ShelterId")
                        .HasColumnName("shelter_id")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("ShelterId");

                    b.ToTable("needs");
                });

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.Shelter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnName("address")
                        .HasColumnType("text");

                    b.Property<string>("CoverUrl")
                        .HasColumnName("cover_url")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnName("logo_url")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("shelters");
                });

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.ShelterVolunteer", b =>
                {
                    b.Property<int>("ShelterId")
                        .HasColumnName("shelter_id")
                        .HasColumnType("integer");

                    b.Property<int>("VolunteerId")
                        .HasColumnName("volunteer_id")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMain")
                        .HasColumnName("is_main")
                        .HasColumnType("boolean");

                    b.Property<int>("Rank")
                        .HasColumnName("rank")
                        .HasColumnType("integer");

                    b.HasKey("ShelterId", "VolunteerId");

                    b.HasIndex("VolunteerId");

                    b.ToTable("shelter_volunteers");
                });

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasColumnType("text");

                    b.Property<string>("ImgUrl")
                        .HasColumnName("img_url")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnName("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("volunteers");
                });

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.Animal", b =>
                {
                    b.HasOne("Mekhnin.Shelter.Data.Shelter.Entities.Shelter", "Shelter")
                        .WithMany("Animals")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.Contact", b =>
                {
                    b.HasOne("Mekhnin.Shelter.Data.Shelter.Entities.Volunteer", "Volunteer")
                        .WithMany("Contacts")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.Need", b =>
                {
                    b.HasOne("Mekhnin.Shelter.Data.Shelter.Entities.Animal", "Animal")
                        .WithMany("Needs")
                        .HasForeignKey("AnimalId");

                    b.HasOne("Mekhnin.Shelter.Data.Shelter.Entities.Shelter", "Shelter")
                        .WithMany("Needs")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mekhnin.Shelter.Data.Shelter.Entities.ShelterVolunteer", b =>
                {
                    b.HasOne("Mekhnin.Shelter.Data.Shelter.Entities.Shelter", "Shelter")
                        .WithMany("ShelterVolunteers")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mekhnin.Shelter.Data.Shelter.Entities.Volunteer", "Volunteer")
                        .WithMany("ShelterVolunteers")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
